/// <summary>)
/// Generated By N-UIKit/UIFlagGenerater
/// 自动生成，请勿手动修改
/// <summary>)

public enum UIPackage
{
	None		= -1,
	ui_common		= 0,
	ui_message		= 1,
	ui_start		= 2,
}

public enum UIFlag
{
	None			= -1,
	/// <summary>)
	/// ui_common
	/// <summary>)
	LoadingPanel			= 0,


	/// <summary>)
	/// ui_message
	/// <summary>)
	ui_dialog			= 1000,
	ui_toast,
	ui_wait,


	/// <summary>)
	/// ui_start
	/// <summary>)


}


/// <summary>
/// UIFlagExtention
/// </summary>
public static class UIFlagExtention
{
	public static void Test()
	{
		var f = UIFlag.ui_dialog;
		f.GetUIPackage();
	}
	public static UIPackage GetUIPackage(this UIFlag flag)
	{
		if(flag == UIFlag.None) return UIPackage.None;
		int result = (int)flag / 1000;
		return (UIPackage)result;
	}
}
